---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rohit
  template:
    metadata:
      labels:
        app: rohit
    spec:
      containers:
      - name: suneel
        image: rohit5683/feb-docker:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: rohit-service
spec:
  selector:
    app: rohit
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
